# Generated by Django 5.2.12 on 2026-03-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT (Empresas)'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('PPT', 'Permiso por Proteccion Temporal')], default='CC', max_length=10),
        ),
    ]
