# Generated by Django 5.2.12 on 2026-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre.'}, help_text='Nombre único para entrar al sistema.', max_length=150, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
