# Generated by Django 5.2.12 on 2026-03-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0002_alter_cita_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('fecha_hora',)},
        ),
    ]
