# Generated by Django 5.2.12 on 2026-04-06 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0004_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamiento.cita'),
        ),
    ]
