# Generated by Django 5.2.12 on 2026-03-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrs',
            options={'verbose_name_plural': 'PQRS'},
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='asunto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='respuesta_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta del Administrador'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='tipo',
            field=models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=20),
        ),
    ]
